[versions]

agp = "8.10.0"
#noinspection GradleDependency
foundation = "1.7.8"
hilt = "2.56.2"
ksp = "2.1.20-1.0.31"
kotlin = "2.1.21"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

lifecycleViewmodelCompose = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.05.01"
composeMaterial3 = "1.3.2"
composeMaterialIconsCore = "1.7.8"

media3Ui = "1.7.1"
media3Exoplayer = "1.7.1"
media3Session = "1.7.1"

concurrentFuturesKtx = "1.2.0"
kotlinxCoroutinesGuava = "1.10.2"

xr-compose = "1.0.0-alpha05"
runtime = "1.0.0-alpha05"
xr-scenecore = "1.0.0-alpha05"
xr-arcore = "1.0.0-alpha05"
xr-material3XR = "1.0.0-alpha10"

[libraries]
# androidx media3
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Session" }

# jetbrains

androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-runtime = { module = "androidx.xr.runtime:runtime", version.ref = "runtime" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesGuava" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# androidx
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-compose-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "composeMaterial3" }

androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "composeMaterialIconsCore" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }

# androidx XR
androidx-xr-compose = { group = "androidx.xr.compose", name = "compose", version.ref = "xr-compose" }
androidx-xr-arcore = { module = "androidx.xr.arcore:arcore", version.ref = "xr-arcore" }
androidx-xr-material3 = { module = "androidx.xr.compose.material3:material3", version.ref = "xr-material3XR" }

# test
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

